include:
  - board: nice_nano_v2
    shield: corne_left
    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: corne_right
    snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: settings_reset