include:
  - board: nice_nano_v2
    shield: cabanatkl_left
    snippet: zmk-usb-logging

  - board: nice_nano_v2
    shield:  cabanatkl_right
    snippet: zmk-usb-logging

  - board: nice_nano_v2
    shield: settings_reset