include:
  - board: nice_nano_v2
    shield: slaetiny_left ssd1306_128x32
    snippet: zmk-usb-logging 
    
  - board: nice_nano_v2
    shield: slaetiny_right ssd1306_128x32
    snippet: zmk-usb-logging
    
  - board: nice_nano_v2
    shield: settings_reset
