include:
  - board: nice_nano_v2
    shield: slaethandwire_left
    snippet: zmk-usb-logging

  - board: nice_nano_v2
    shield:  slaethandwire_right
    snippet: zmk-usb-logging

  - board: nice_nano_v2
    shield: settings_reset